import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { existsSync, chmodSync, readFileSync, writeFileSync } from "node:fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// resources/ already lives at the plugin root next to main.js (not a separate
// source location), so nothing needs copying -- just make sure the exec bit
// survives git checkouts, which don't reliably preserve it.
function ensureResourcesExecutable() {
  for (const f of ["resources/hook-bridge.sh", "resources/pty_helper.py"]) {
    if (existsSync(f)) chmodSync(f, 0o755);
  }
}

// Obsidian only auto-loads a single styles.css per plugin, but xterm.js needs
// its own CSS for correct rendering (cursor, selection, font measuring).
// Concatenate our authored CSS with xterm's at build time rather than
// requiring a separate CSS bundler entry point.
function buildStylesheet() {
  const custom = readFileSync("src/css/custom.css", "utf8");
  const xterm = readFileSync("node_modules/@xterm/xterm/css/xterm.css", "utf8");
  const banner = "/* GENERATED by esbuild.config.mjs from src/css/custom.css + @xterm/xterm/css/xterm.css */\n";
  writeFileSync("styles.css", banner + custom + "\n" + xterm);
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [
    {
      name: "chmod-resources",
      setup(build) {
        build.onEnd(() => {
          ensureResourcesExecutable();
          buildStylesheet();
        });
      },
    },
  ],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
