/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CitedPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");
var path4 = __toESM(require("path"));

// src/claude/claudeBin.ts
var import_child_process = require("child_process");
var import_fs = require("fs");
var import_util = require("util");
var execFileAsync = (0, import_util.promisify)(import_child_process.execFile);
var CLAUDE_BIN_CANDIDATES = ["/usr/local/bin/claude", "/opt/homebrew/bin/claude"];
function resolveUserShell() {
  const shell = process.env.SHELL;
  return typeof shell === "string" && shell ? shell : "/bin/zsh";
}
async function tryLoginShellWhich(bin) {
  var _a;
  const loginShell = resolveUserShell();
  try {
    const { stdout } = await execFileAsync(loginShell, ["-lic", `which ${bin}`], { timeout: 5e3 });
    const resolved = (_a = stdout.trim().split("\n").pop()) == null ? void 0 : _a.trim();
    return resolved && (0, import_fs.existsSync)(resolved) ? resolved : null;
  } catch (e) {
    return null;
  }
}
async function resolveClaudeBin() {
  const loginShellPath = await tryLoginShellWhich("claude");
  if (loginShellPath)
    return loginShellPath;
  for (const candidate of CLAUDE_BIN_CANDIDATES) {
    if ((0, import_fs.existsSync)(candidate))
      return candidate;
  }
  return "claude";
}

// src/claude/queryVault.ts
var import_child_process2 = require("child_process");
var import_fs2 = require("fs");
var readline = __toESM(require("readline"));
var path = __toESM(require("path"));
var TIMEOUT_MS = 12e4;
function toVaultRelative(vaultBasePath, cwd, absOrRel) {
  const abs = path.isAbsolute(absOrRel) ? absOrRel : path.join(cwd, absOrRel);
  return path.relative(vaultBasePath, abs);
}
function extractText(content) {
  if (typeof content === "string")
    return content;
  if (Array.isArray(content)) {
    return content.map((block) => block && typeof block === "object" && "text" in block ? String(block.text) : "").join("\n");
  }
  return "";
}
function stripLineNumberPrefixes(text) {
  return text.split("\n").map((line) => line.replace(/^\s*\d+\t/, "")).join("\n");
}
function splitGrepResultByFile(resultText) {
  var _a, _b;
  const linesByFile = /* @__PURE__ */ new Map();
  for (const line of resultText.split("\n")) {
    const match = line.match(/^(.+?):(\d+):(.*)$/);
    if (!match)
      continue;
    const file = (_a = match[1]) == null ? void 0 : _a.replace(/^\.\//, "");
    const content = match[3];
    if (file === void 0 || content === void 0)
      continue;
    const lines = (_b = linesByFile.get(file)) != null ? _b : [];
    lines.push(content);
    linesByFile.set(file, lines);
  }
  const byFile = /* @__PURE__ */ new Map();
  for (const [file, lines] of linesByFile)
    byFile.set(file, lines.join("\n"));
  return byFile;
}
function describeToolUse(block) {
  var _a;
  const name = typeof block.name === "string" ? block.name : "unknown";
  const input = (_a = block.input) != null ? _a : {};
  if (name === "Read" && typeof input.file_path === "string")
    return `Reading ${path.basename(input.file_path)}`;
  if (name === "Grep" && typeof input.pattern === "string")
    return `Searching for "${input.pattern}"`;
  if (name === "Glob" && typeof input.pattern === "string")
    return `Listing files matching "${input.pattern}"`;
  return `Running ${name}`;
}
function describeAssistantEvent(event, turn, maxTurns) {
  const message = event.message;
  const blocks = Array.isArray(message == null ? void 0 : message.content) ? message.content : [];
  const toolBlock = blocks.find((b) => (b == null ? void 0 : b.type) === "tool_use");
  const label = toolBlock ? describeToolUse(toolBlock) : "Reviewing what it's found\u2026";
  return { turn, maxTurns, label };
}
function parseTranscript(lines, vaultBasePath, cwd) {
  var _a;
  const pendingByToolUseId = /* @__PURE__ */ new Map();
  const toolCalls = [];
  let rawAnswer = "";
  let sessionId = null;
  for (const line of lines) {
    if (!line.trim())
      continue;
    let event;
    try {
      event = JSON.parse(line);
    } catch (e) {
      continue;
    }
    const message = event.message;
    if (event.type === "assistant" && Array.isArray(message == null ? void 0 : message.content)) {
      for (const block of message.content) {
        if ((block == null ? void 0 : block.type) !== "tool_use" || typeof block.id !== "string")
          continue;
        const input = (_a = block.input) != null ? _a : {};
        const toolName = typeof block.name === "string" ? block.name : "unknown";
        const file = toolName === "Read" && typeof input.file_path === "string" ? toVaultRelative(vaultBasePath, cwd, input.file_path) : null;
        pendingByToolUseId.set(block.id, { toolUseId: block.id, toolName, file });
      }
    } else if (event.type === "user" && Array.isArray(message == null ? void 0 : message.content)) {
      for (const block of message.content) {
        if ((block == null ? void 0 : block.type) !== "tool_result" || typeof block.tool_use_id !== "string")
          continue;
        const pending = pendingByToolUseId.get(block.tool_use_id);
        if (!pending)
          continue;
        const text = extractText(block.content);
        if (pending.toolName === "Grep") {
          for (const [file, matchedText] of splitGrepResultByFile(text)) {
            const vaultRelFile = toVaultRelative(vaultBasePath, cwd, file);
            toolCalls.push({ toolUseId: pending.toolUseId, toolName: pending.toolName, file: vaultRelFile, resultText: matchedText });
          }
          continue;
        }
        if (pending.toolName !== "Read")
          continue;
        toolCalls.push({
          toolUseId: pending.toolUseId,
          toolName: pending.toolName,
          file: pending.file,
          resultText: stripLineNumberPrefixes(text)
        });
      }
    } else if (event.type === "result" && typeof event.result === "string") {
      rawAnswer = event.result;
    } else if (event.type === "system" && typeof event.session_id === "string") {
      sessionId = event.session_id;
    }
  }
  return { rawAnswer, toolCalls, sessionId };
}
async function runVaultQuery(claudeBin, vaultBasePath, prompt, maxTurns, scopePath, resumeSessionId, onProgress) {
  const queryCwd = scopePath ? path.join(vaultBasePath, scopePath) : vaultBasePath;
  if (scopePath && (!(0, import_fs2.existsSync)(queryCwd) || !(0, import_fs2.statSync)(queryCwd).isDirectory())) {
    throw new Error(`Cited: scope folder "${scopePath}" doesn't exist in this vault.`);
  }
  return new Promise((resolve, reject) => {
    const args = [
      "-p",
      prompt,
      "--allowedTools",
      "Read,Grep,Glob",
      // Belt-and-suspenders: observed --allowedTools alone still letting a
      // Bash tool_use through in manual testing (likely a quirk of testing
      // from a nested claude session, but cheap to guard against
      // regardless) -- this plugin's entire premise is read-only search,
      // so Bash is explicitly denied on top of only allow-listing the
      // read-only tools.
      "--disallowedTools",
      "Bash",
      "--output-format",
      "stream-json",
      "--verbose",
      "--max-turns",
      String(maxTurns)
    ];
    if (resumeSessionId)
      args.push("--resume", resumeSessionId);
    const child = (0, import_child_process2.spawn)(claudeBin, args, { cwd: queryCwd });
    const rawLines = [];
    let stderr = "";
    let settled = false;
    const timer = setTimeout(() => {
      if (settled)
        return;
      settled = true;
      child.kill();
      reject(new Error("Cited: query to claude timed out"));
    }, TIMEOUT_MS);
    let turn = 0;
    const rl = readline.createInterface({ input: child.stdout });
    rl.on("line", (line) => {
      rawLines.push(line);
      if (!onProgress || !line.trim())
        return;
      let event;
      try {
        event = JSON.parse(line);
      } catch (e) {
        return;
      }
      if (event.type !== "assistant")
        return;
      turn++;
      onProgress(describeAssistantEvent(event, turn, maxTurns));
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });
    child.on("error", (err) => {
      if (settled)
        return;
      settled = true;
      clearTimeout(timer);
      reject(err);
    });
    child.on("close", (code) => {
      if (settled)
        return;
      settled = true;
      clearTimeout(timer);
      const result = parseTranscript(rawLines, vaultBasePath, queryCwd);
      if (code !== 0 && !result.rawAnswer) {
        reject(new Error(`Cited: claude exited with code ${code}${stderr ? `: ${stderr.slice(0, 2e3)}` : ""}`));
        return;
      }
      resolve(result);
    });
  });
}

// src/claude/parseAnswer.ts
function buildVaultQuestionPrompt(question, scopePath) {
  const scopeInstruction = scopePath ? `

Your search is already restricted to the "${scopePath}" folder -- that's your current working directory, so Glob/Grep with no path argument only look inside it. Don't pass an absolute path or ".." to search outside it.` : "";
  return `You are answering a question about the user's Obsidian vault (the current working directory). Use the Read, Grep, and Glob tools to search the vault and find the actual notes that answer the question -- don't answer from general knowledge alone if the vault has relevant notes; search first.${scopeInstruction}

Question: ${question}

Once you're confident in your answer, respond with ONLY a raw JSON object, no markdown fences, no explanation outside the JSON, in exactly this shape:
{
  "answer": "<your answer, plain text or simple markdown>",
  "claims": [
    {
      "text": "<a specific claim or sentence, copied verbatim/word-for-word from your answer above -- must be an exact substring of "answer", not a paraphrase of it>",
      "citations": [
        { "file": "<vault-relative path you actually opened with Read or matched with Grep>", "excerpt": "<the specific text from that file supporting this claim>", "type": "quote" or "inferred" }
      ]
    }
  ]
}

"quote" means the excerpt is copied verbatim from the file. "inferred" means you synthesized or paraphrased across the passage rather than quoting it -- the excerpt should still be the specific passage you drew on, just not necessarily an exact substring. Each claim's own "text" field must always be an exact substring of "answer" though, regardless of the citation type -- this is what lets the app link a claim back to the right spot in your answer, so never summarize or reword it there.

Every "file" must be a file you actually opened with Read or matched with Grep during this turn -- never cite a file you didn't look at. If part of your answer isn't backed by a specific vault file, just omit citations for that claim (or omit the claim from the list entirely) rather than inventing one. If nothing in the vault is relevant, return an empty claims array.`;
}
function parseJsonLoose(text) {
  try {
    return JSON.parse(text);
  } catch (e) {
  }
  const match = text.match(/\{[\s\S]*\}/);
  if (match) {
    try {
      return JSON.parse(match[0]);
    } catch (e) {
    }
  }
  return null;
}
function isWithinScope(file, scopePath) {
  const normalizedScope = scopePath.replace(/\/+$/, "");
  return file === normalizedScope || file.startsWith(`${normalizedScope}/`);
}
function parseVaultAnswer(question, turnId, rawAnswer, toolCalls, scopePath) {
  const parsed = parseJsonLoose(rawAnswer);
  if (!parsed || typeof parsed.answer !== "string") {
    return {
      turnId,
      question,
      answer: rawAnswer.trim() || "(no response)",
      claims: [],
      createdAt: Date.now(),
      scopePath
    };
  }
  const poolByFile = /* @__PURE__ */ new Map();
  for (const call of toolCalls) {
    if (!call.file)
      continue;
    if (scopePath && !isWithinScope(call.file, scopePath))
      continue;
    const existing = poolByFile.get(call.file);
    poolByFile.set(call.file, existing ? `${existing}
${call.resultText}` : call.resultText);
  }
  if (scopePath) {
    const prefix = `${scopePath.replace(/\/+$/, "")}/`;
    for (const [file, text] of [...poolByFile]) {
      if (!file.startsWith(prefix))
        continue;
      const scopeRelative = file.slice(prefix.length);
      if (scopeRelative && !poolByFile.has(scopeRelative))
        poolByFile.set(scopeRelative, text);
    }
  }
  const rawClaims = Array.isArray(parsed.claims) ? parsed.claims : [];
  const claims = [];
  let claimCounter = 0;
  let citationCounter = 0;
  for (const rawClaim of rawClaims) {
    if (typeof rawClaim.text !== "string")
      continue;
    const rawCitations = Array.isArray(rawClaim.citations) ? rawClaim.citations : [];
    const citations = [];
    for (const rawCitation of rawCitations) {
      if (typeof rawCitation.file !== "string" || typeof rawCitation.excerpt !== "string")
        continue;
      const sourceText = poolByFile.get(rawCitation.file);
      if (sourceText === void 0)
        continue;
      const excerpt = rawCitation.excerpt.trim();
      if (!excerpt)
        continue;
      const matchIndex = sourceText.indexOf(excerpt);
      const verified = matchIndex !== -1;
      const requestedType = rawCitation.type === "inferred" ? "inferred" : "quote";
      citations.push({
        id: `c${++citationCounter}`,
        file: rawCitation.file,
        type: verified ? requestedType : "inferred",
        excerpt,
        sourceText,
        location: verified ? { from: matchIndex, to: matchIndex + excerpt.length } : null,
        verified,
        // Stamped in by ConversationStore right after this CitedAnswer is
        // built, using the Obsidian vault API -- this module has no
        // Obsidian dependency and stays that way.
        capturedMtime: null,
        stale: false
      });
    }
    if (citations.length === 0)
      continue;
    claims.push({ id: `claim${++claimCounter}`, text: rawClaim.text, citations });
  }
  return {
    turnId,
    question,
    answer: parsed.answer,
    claims,
    createdAt: Date.now(),
    scopePath
  };
}

// src/state/ConversationStore.ts
var fs = __toESM(require("fs/promises"));
var path2 = __toESM(require("path"));

// src/util/emitter.ts
var TypedEmitter = class {
  constructor() {
    this.listeners = /* @__PURE__ */ new Map();
  }
  on(event, listener) {
    let set = this.listeners.get(event);
    if (!set) {
      set = /* @__PURE__ */ new Set();
      this.listeners.set(event, set);
    }
    set.add(listener);
  }
  off(event, listener) {
    var _a;
    (_a = this.listeners.get(event)) == null ? void 0 : _a.delete(listener);
  }
  emit(event, ...args) {
    const set = this.listeners.get(event);
    if (!set)
      return;
    for (const listener of set)
      listener(...args);
  }
};

// src/util/errors.ts
function errorMessage(err) {
  return err instanceof Error ? err.message : String(err);
}
function isEnoent(err) {
  return typeof err === "object" && err !== null && "code" in err && err.code === "ENOENT";
}

// src/state/ConversationStore.ts
var MAX_ARCHIVED_CONVERSATIONS = 50;
var ConversationStore = class extends TypedEmitter {
  constructor(logFilePath, runQuery, statMtime) {
    super();
    this.logFilePath = logFilePath;
    this.runQuery = runQuery;
    this.statMtime = statMtime;
    this.archived = [];
    this.loading = false;
    this.error = null;
    this.loaded = false;
    this.turnCounter = 0;
    this.progress = null;
    this.current = this.newConversation();
  }
  async load() {
    if (this.loaded)
      return;
    try {
      const raw = await fs.readFile(this.logFilePath, "utf8");
      const parsed = raw.trim() ? JSON.parse(raw) : null;
      if ((parsed == null ? void 0 : parsed.archived) && Array.isArray(parsed.archived))
        this.archived = parsed.archived;
      if (parsed == null ? void 0 : parsed.current)
        this.current = parsed.current;
    } catch (err) {
      if (!isEnoent(err))
        throw err;
    }
    this.loaded = true;
    this.emit("change");
  }
  getConversation() {
    return this.current;
  }
  isLoading() {
    return this.loading;
  }
  getError() {
    return this.error;
  }
  getProgress() {
    return this.progress;
  }
  async askQuestion(question, scopePath = null) {
    this.loading = true;
    this.error = null;
    this.progress = null;
    this.emit("change");
    const turnId = `turn${++this.turnCounter}`;
    try {
      const result = await this.runQuery(question, this.current.sessionId, scopePath, (progress) => {
        this.progress = progress;
        this.emit("change");
      });
      const answer = parseVaultAnswer(question, turnId, result.rawAnswer, result.toolCalls, scopePath);
      for (const claim of answer.claims) {
        for (const citation of claim.citations) {
          citation.capturedMtime = this.statMtime(citation.file);
        }
      }
      this.current.turns.push(answer);
      if (result.sessionId)
        this.current.sessionId = result.sessionId;
      this.loading = false;
      this.progress = null;
      await this.persist();
    } catch (err) {
      this.loading = false;
      this.progress = null;
      this.error = errorMessage(err);
    }
    this.emit("change");
  }
  async startNewConversation() {
    this.archiveCurrent();
    this.current = this.newConversation();
    this.error = null;
    await this.persist();
    this.emit("change");
  }
  listArchived() {
    return [...this.archived];
  }
  /** Removes one archived conversation permanently -- there's no undo path
   *  for this (unlike Terminus's "Recently resolved" list backing its bulk
   *  actions), so callers are expected to confirm with the user first. A
   *  no-op if `id` isn't found (e.g. a stale reference from an already
   *  re-rendered history list). */
  async deleteConversation(id) {
    const index = this.archived.findIndex((c) => c.id === id);
    if (index === -1)
      return;
    this.archived.splice(index, 1);
    await this.persist();
    this.emit("change");
  }
  /** Wipes every archived conversation. Same no-undo caveat as
   *  deleteConversation. Deliberately leaves the current live conversation
   *  untouched -- "clear history" means past conversations, not whatever
   *  you're actively in the middle of. */
  async clearHistory() {
    if (this.archived.length === 0)
      return;
    this.archived = [];
    await this.persist();
    this.emit("change");
  }
  /** Swaps an archived conversation back in as the live one -- e.g. from a
   *  history picker -- so the user can keep chatting in it: askQuestion
   *  resumes using its own stored sessionId, same as any other turn (this
   *  works even for sessions well older than the immediately-preceding
   *  one -- verified manually before building this). Whatever was active
   *  gets archived first if it has any turns, same as starting fresh. */
  openConversation(id) {
    const index = this.archived.findIndex((c) => c.id === id);
    if (index === -1)
      return;
    const [reopened] = this.archived.splice(index, 1);
    if (!reopened)
      return;
    this.archiveCurrent();
    this.current = reopened;
    this.error = null;
    void this.persist();
    this.emit("change");
  }
  /** ChatView calls this when an inline marker is clicked; CitedView
   *  listens for it to scroll to and expand the matching claim. */
  focusClaim(claimId) {
    this.emit("focus-claim", claimId);
  }
  /** Called from main.ts's vault "modify" listener. Flags every citation
   *  across the current conversation pointing at `filePath` as stale -- see
   *  model.ts's Citation.stale doc for what that does (and doesn't) do. */
  markFileStale(filePath) {
    let changed = false;
    for (const turn of this.current.turns) {
      for (const claim of turn.claims) {
        for (const citation of claim.citations) {
          if (citation.file === filePath && !citation.stale) {
            citation.stale = true;
            changed = true;
          }
        }
      }
    }
    if (changed) {
      void this.persist();
      this.emit("change");
    }
  }
  archiveCurrent() {
    if (this.current.turns.length === 0)
      return;
    this.archived.unshift(this.current);
    if (this.archived.length > MAX_ARCHIVED_CONVERSATIONS)
      this.archived.length = MAX_ARCHIVED_CONVERSATIONS;
  }
  newConversation() {
    return { id: `conv${Date.now()}`, sessionId: null, turns: [], createdAt: Date.now() };
  }
  async persist() {
    await fs.mkdir(path2.dirname(this.logFilePath), { recursive: true });
    const payload = { current: this.current, archived: this.archived };
    await fs.writeFile(this.logFilePath, JSON.stringify(payload, null, 2), "utf8");
  }
};

// src/views/CitedView.ts
var import_obsidian = require("obsidian");
var path3 = __toESM(require("path"));

// src/util/stripMarkdown.ts
function stripMarkdown(text) {
  return text.replace(/`([^`]+)`/g, "$1").replace(/\*\*([^*]+)\*\*/g, "$1").replace(/__([^_]+)__/g, "$1").replace(/\*([^*]+)\*/g, "$1").replace(/(?<![a-zA-Z0-9])_([^_]+)_(?![a-zA-Z0-9])/g, "$1").replace(/~~([^~]+)~~/g, "$1").replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2").replace(/\[\[([^\]]+)\]\]/g, "$1").replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").trim();
}

// src/views/CitedView.ts
var CITED_VIEW_TYPE = "cited-results";
var CitedView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    // Persisted across re-renders (this view fully rebuilds its DOM on every
    // store "change", same as Terminus's PendingChangesView) so an unrelated
    // event -- a new turn, a staleness update from an unrelated file edit --
    // doesn't silently re-collapse a row the user had opened. Without this,
    // every store "change" would reset a per-row closure-local `expanded`
    // boolean back to false on rebuild.
    this.expandedClaimIds = /* @__PURE__ */ new Set();
    this.expandedCitationIds = /* @__PURE__ */ new Set();
    // Turn sections default open (matching Terminus's terminal groups), so
    // this tracks the exception -- turns the user explicitly collapsed --
    // rather than which ones are open.
    this.collapsedTurnIds = /* @__PURE__ */ new Set();
    this.handleFocusClaim = (claimId) => {
      this.expandedClaimIds.add(claimId);
      this.render();
      const row = this.contentEl.querySelector(`[data-claim-id="${CSS.escape(claimId)}"]`);
      row == null ? void 0 : row.scrollIntoView({ behavior: "smooth", block: "center" });
    };
    this.render = () => {
      const container = this.contentEl;
      container.empty();
      container.addClass("cited-view");
      const conversation = this.plugin.conversationStore.getConversation();
      const turnsWithClaims = conversation.turns.filter((t) => t.claims.length > 0);
      if (turnsWithClaims.length === 0) {
        container.createDiv({ cls: "cited-status", text: "No grounded citations yet -- ask Cited a question." });
        return;
      }
      for (const turn of turnsWithClaims) {
        this.renderTurn(container, turn);
      }
    };
  }
  getViewType() {
    return CITED_VIEW_TYPE;
  }
  getDisplayText() {
    return "Cited sources";
  }
  getIcon() {
    return "quote-glyph";
  }
  async onOpen() {
    this.plugin.conversationStore.on("change", this.render);
    this.plugin.conversationStore.on("focus-claim", this.handleFocusClaim);
    this.render();
  }
  async onClose() {
    this.plugin.conversationStore.off("change", this.render);
    this.plugin.conversationStore.off("focus-claim", this.handleFocusClaim);
  }
  /** Same collapsible-group idiom as Terminus's per-terminal groups in
   *  PendingChangesView (chevron + header + hidden list, default open) --
   *  one section per question, so a long-running conversation doesn't turn
   *  into one giant undifferentiated citation list. */
  renderTurn(container, turn) {
    const collapsed = this.collapsedTurnIds.has(turn.turnId);
    const section = container.createDiv({ cls: "cited-turn-section" });
    const header = section.createDiv({ cls: "cited-turn-section-header" });
    const chevron = header.createEl("span", { cls: "cited-chevron", text: collapsed ? "\u25B8" : "\u25BE" });
    const headerText = header.createDiv({ cls: "cited-turn-section-text" });
    headerText.createDiv({ cls: "cited-turn-section-question", text: turn.question });
    const citationCount = turn.claims.reduce((sum, c) => sum + c.citations.length, 0);
    const fileCount = new Set(turn.claims.flatMap((c) => c.citations.map((cit) => cit.file))).size;
    const scopeSuffix = turn.scopePath ? ` \xB7 in ${turn.scopePath}` : "";
    headerText.createDiv({
      cls: "cited-turn-section-meta",
      text: `${citationCount} ${citationCount === 1 ? "reference" : "references"} \xB7 ${fileCount} ${fileCount === 1 ? "file" : "files"}${scopeSuffix}`
    });
    const list = section.createDiv({ cls: "cited-claims-list" });
    list.toggle(!collapsed);
    for (const claim of turn.claims) {
      this.renderClaim(list, claim);
    }
    header.addEventListener("click", () => {
      const willBeCollapsed = !this.collapsedTurnIds.has(turn.turnId);
      if (willBeCollapsed)
        this.collapsedTurnIds.add(turn.turnId);
      else
        this.collapsedTurnIds.delete(turn.turnId);
      list.toggle(!willBeCollapsed);
      chevron.setText(willBeCollapsed ? "\u25B8" : "\u25BE");
    });
  }
  /** Same three-part collapsible idiom as Terminus's PendingChangesView
   *  (chevron + hidden body + toggle-on-click), reused here for a
   *  claim -> its contributing files, and again inside renderCitation for
   *  file -> its highlighted excerpt. */
  renderClaim(list, claim) {
    const expanded = this.expandedClaimIds.has(claim.id);
    const row = list.createDiv({ cls: "cited-claim" });
    row.setAttribute("data-claim-id", claim.id);
    row.toggleClass("is-expanded", expanded);
    const summary = row.createDiv({ cls: "cited-claim-summary" });
    summary.toggleClass("is-expanded", expanded);
    const chevron = summary.createEl("span", { cls: "cited-chevron", text: expanded ? "\u25BE" : "\u25B8" });
    const info = summary.createDiv({ cls: "cited-claim-info" });
    info.createEl("div", { cls: "cited-claim-text", text: stripMarkdown(claim.text) });
    const fileCount = new Set(claim.citations.map((c) => c.file)).size;
    info.createEl("div", { cls: "cited-claim-meta", text: `${fileCount} ${fileCount === 1 ? "file" : "files"}` });
    const body = row.createDiv({ cls: "cited-claim-body" });
    body.toggle(expanded);
    for (const citation of claim.citations) {
      this.renderCitation(body, citation);
    }
    summary.addEventListener("click", () => {
      const next = !this.expandedClaimIds.has(claim.id);
      if (next)
        this.expandedClaimIds.add(claim.id);
      else
        this.expandedClaimIds.delete(claim.id);
      body.toggle(next);
      chevron.setText(next ? "\u25BE" : "\u25B8");
      row.toggleClass("is-expanded", next);
      summary.toggleClass("is-expanded", next);
    });
  }
  renderCitation(container, citation) {
    const expanded = this.expandedCitationIds.has(citation.id);
    const row = container.createDiv({ cls: "cited-citation" });
    row.toggleClass("is-expanded", expanded);
    const summary = row.createDiv({ cls: "cited-citation-summary" });
    summary.toggleClass("is-expanded", expanded);
    const chevron = summary.createEl("span", { cls: "cited-chevron", text: expanded ? "\u25BE" : "\u25B8" });
    const info = summary.createDiv({ cls: "cited-citation-info" });
    info.createEl("span", { cls: "cited-citation-file", text: path3.basename(citation.file) });
    info.createEl("span", {
      cls: `cited-badge cited-badge-${citation.type}`,
      text: citation.type === "quote" ? "quoted" : "inferred"
    });
    if (citation.stale) {
      info.createEl("span", { cls: "cited-badge cited-badge-stale", text: "\u26A0 source changed" });
    }
    const openBtn = summary.createEl("button", { text: "Open", cls: "cited-btn-solid" });
    openBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.app.workspace.openLinkText(citation.file, "", false);
    });
    const body = row.createDiv({ cls: "cited-citation-body" });
    body.toggle(expanded);
    this.renderExcerpt(body, citation);
    summary.addEventListener("click", () => {
      const next = !this.expandedCitationIds.has(citation.id);
      if (next)
        this.expandedCitationIds.add(citation.id);
      else
        this.expandedCitationIds.delete(citation.id);
      body.toggle(next);
      chevron.setText(next ? "\u25BE" : "\u25B8");
      row.toggleClass("is-expanded", next);
      summary.toggleClass("is-expanded", next);
    });
  }
  /** Segment-highlight idiom ported from Terminus's diff/renderDiff.ts
   *  renderDiffLine (a list of plain/emphasized text spans rendered as
   *  span-or-textnode) -- reused here for "highlight this substring inside
   *  this captured excerpt" instead of a line diff. Falls back to plain,
   *  unhighlighted text when there's no verbatim match (inferred/unverified
   *  citations, whose `location` is null -- see parseAnswer.ts). */
  renderExcerpt(container, citation) {
    const pre = container.createEl("pre", { cls: "cited-excerpt" });
    const code = pre.createEl("code");
    if (!citation.location) {
      code.setText(citation.excerpt);
      return;
    }
    const { from, to } = citation.location;
    const context = 80;
    const windowStart = Math.max(0, from - context);
    const windowEnd = Math.min(citation.sourceText.length, to + context);
    if (windowStart > 0)
      code.appendChild(activeDocument.createTextNode("\u2026"));
    if (windowStart < from) {
      code.appendChild(activeDocument.createTextNode(citation.sourceText.slice(windowStart, from)));
    }
    code.createEl("span", { cls: "cited-excerpt-highlight", text: citation.sourceText.slice(from, to) });
    if (to < windowEnd) {
      code.appendChild(activeDocument.createTextNode(citation.sourceText.slice(to, windowEnd)));
    }
    if (windowEnd < citation.sourceText.length)
      code.appendChild(activeDocument.createTextNode("\u2026"));
  }
};

// src/views/ChatView.ts
var import_obsidian6 = require("obsidian");

// src/citations/markers.ts
function findClaimSpans(text, claims) {
  const spans = [];
  let searchFrom = 0;
  for (const claim of claims) {
    const needle = claim.text.trim();
    if (!needle)
      continue;
    const index = text.indexOf(needle, searchFrom);
    if (index === -1)
      continue;
    spans.push({ claim, start: index, end: index + needle.length });
    searchFrom = index + needle.length;
  }
  return spans;
}
function collectTextNodes(container) {
  const ranges = [];
  const walker = activeDocument.createTreeWalker(container, NodeFilter.SHOW_TEXT);
  let offset = 0;
  let node = walker.nextNode();
  while (node) {
    const text = node;
    const length = text.data.length;
    ranges.push({ node: text, start: offset, end: offset + length });
    offset += length;
    node = walker.nextNode();
  }
  return ranges;
}
function insertDomMarkers(container, claims, onClick) {
  const ranges = collectTextNodes(container);
  const renderedText = ranges.map((r) => r.node.data).join("");
  const spans = findClaimSpans(renderedText, claims);
  const ordered = [...spans].sort((a, b) => b.end - a.end);
  for (const span of ordered) {
    const range = ranges.find((r) => span.end > r.start && span.end <= r.end);
    if (!range)
      continue;
    const marker = activeDocument.createElement("sup");
    marker.className = "cited-marker";
    marker.textContent = "\u25CF";
    marker.setAttribute("role", "button");
    marker.setAttribute("aria-label", "Show citation");
    marker.addEventListener("click", (e) => {
      e.preventDefault();
      onClick(span.claim.id);
    });
    const localOffset = span.end - range.start;
    if (localOffset < range.node.data.length)
      range.node.splitText(localOffset);
    range.node.after(marker);
  }
}
function buildFootnotedMarkdown(answer, spans) {
  const numberByClaimId = /* @__PURE__ */ new Map();
  spans.forEach((span, i) => numberByClaimId.set(span.claim.id, i + 1));
  let body = answer;
  const orderedByEndDescending = [...spans].sort((a, b) => b.end - a.end);
  for (const span of orderedByEndDescending) {
    const n = numberByClaimId.get(span.claim.id);
    body = `${body.slice(0, span.end)}[^${n}]${body.slice(span.end)}`;
  }
  const footnoteLines = spans.map((span) => {
    const n = numberByClaimId.get(span.claim.id);
    const parts = span.claim.citations.map(
      (c) => `[[${c.file}]] \u2014 "${c.excerpt.replace(/\s+/g, " ").trim()}" (${c.type})`
    );
    return `[^${n}]: ${parts.join("; ")}`;
  });
  return footnoteLines.length > 0 ? `${body}

## Sources

${footnoteLines.join("\n")}
` : body;
}

// src/export/exportToNote.ts
var import_obsidian2 = require("obsidian");
function sanitizeForFilename(text) {
  return text.replace(/[\\/:*?"<>|]/g, "").trim().slice(0, 60);
}
async function exportAnswerToNote(app, answer, folder) {
  const spans = findClaimSpans(answer.answer, answer.claims);
  const body = buildFootnotedMarkdown(answer.answer, spans);
  const date = new Date(answer.createdAt).toISOString().slice(0, 10);
  const titleFragment = sanitizeForFilename(answer.question) || "Untitled question";
  const content = `# ${answer.question}

${body}`;
  const folderPath = (0, import_obsidian2.normalizePath)(folder.trim());
  if (folderPath && folderPath !== "." && !app.vault.getAbstractFileByPath(folderPath)) {
    await app.vault.createFolder(folderPath);
  }
  const basePath = folderPath && folderPath !== "." ? `${folderPath}/Cited - ${titleFragment} - ${date}` : `Cited - ${titleFragment} - ${date}`;
  let file;
  for (let suffix = 0; ; suffix++) {
    const path5 = (0, import_obsidian2.normalizePath)(`${basePath}${suffix > 0 ? ` (${suffix})` : ""}.md`);
    if (app.vault.getAbstractFileByPath(path5))
      continue;
    file = await app.vault.create(path5, content);
    break;
  }
  await app.workspace.getLeaf(true).openFile(file);
}

// src/modals/ConversationHistoryModal.ts
var import_obsidian4 = require("obsidian");

// src/modals/ConfirmModal.ts
var import_obsidian3 = require("obsidian");
var ConfirmModal = class extends import_obsidian3.Modal {
  constructor(app, title, message, confirmText) {
    super(app);
    this.title = title;
    this.message = message;
    this.confirmText = confirmText;
    this.resolvePromise = null;
  }
  static confirm(app, title, message, confirmText = "Confirm") {
    return new Promise((resolve) => {
      const modal = new ConfirmModal(app, title, message, confirmText);
      modal.resolvePromise = resolve;
      modal.open();
    });
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const buttonRow = contentEl.createDiv({ cls: "cited-confirm-modal-actions" });
    buttonRow.createEl("button", { text: "Cancel" }).addEventListener("click", () => this.resolve(false));
    buttonRow.createEl("button", { text: this.confirmText, cls: "mod-cta" }).addEventListener(
      "click",
      () => this.resolve(true)
    );
  }
  onClose() {
    this.contentEl.empty();
    this.resolve(false);
  }
  resolve(value) {
    if (!this.resolvePromise)
      return;
    const resolvePromise = this.resolvePromise;
    this.resolvePromise = null;
    resolvePromise(value);
    this.close();
  }
};

// src/modals/ConversationHistoryModal.ts
var ConversationHistoryModal = class extends import_obsidian4.Modal {
  constructor(app, conversations, onSelect, onDelete) {
    super(app);
    this.onSelect = onSelect;
    this.onDelete = onDelete;
    this.searchQuery = "";
    this.conversations = [...conversations];
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("cited-history-modal");
    contentEl.createEl("h3", { text: "Conversation history" });
    const searchInput = contentEl.createEl("input", {
      type: "text",
      placeholder: "Search past questions\u2026",
      cls: "cited-history-search"
    });
    searchInput.addEventListener("input", () => {
      this.searchQuery = searchInput.value;
      this.render();
    });
    this.list = contentEl.createDiv({ cls: "cited-history-list" });
    searchInput.focus();
    this.render();
  }
  onClose() {
    this.contentEl.empty();
  }
  render() {
    this.list.empty();
    const query = this.searchQuery.trim().toLowerCase();
    const filtered = query ? this.conversations.filter((c) => c.turns.some((t) => t.question.toLowerCase().includes(query))) : this.conversations;
    if (filtered.length === 0) {
      this.list.createDiv({ cls: "cited-status", text: this.conversations.length === 0 ? "No conversation history yet" : "No matching conversations" });
      return;
    }
    for (const conversation of filtered) {
      this.renderRow(this.list, conversation);
    }
  }
  renderRow(list, conversation) {
    var _a, _b;
    const firstQuestion = (_b = (_a = conversation.turns[0]) == null ? void 0 : _a.question) != null ? _b : "(empty conversation)";
    const row = list.createDiv({ cls: "cited-history-row" });
    const info = row.createDiv({ cls: "cited-history-row-info" });
    info.createEl("div", { cls: "cited-history-row-question", text: firstQuestion });
    const meta = info.createDiv({ cls: "cited-history-row-meta" });
    meta.createEl("span", {
      text: `${conversation.turns.length} ${conversation.turns.length === 1 ? "turn" : "turns"}`
    });
    meta.createEl("span", { text: new Date(conversation.createdAt).toLocaleString() });
    const deleteBtn = row.createEl("button", { cls: "cited-history-delete", attr: { "aria-label": "Delete conversation" } });
    (0, import_obsidian4.setIcon)(deleteBtn, "trash-2");
    deleteBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      void this.confirmAndDelete(conversation);
    });
    row.addEventListener("click", () => {
      this.onSelect(conversation.id);
      this.close();
    });
  }
  async confirmAndDelete(conversation) {
    var _a, _b;
    const label = (_b = (_a = conversation.turns[0]) == null ? void 0 : _a.question) != null ? _b : "this conversation";
    const confirmed = await ConfirmModal.confirm(
      this.app,
      "Delete conversation?",
      `This permanently deletes "${label}" (${conversation.turns.length} ${conversation.turns.length === 1 ? "turn" : "turns"}). This can't be undone.`,
      "Delete"
    );
    if (!confirmed)
      return;
    await this.onDelete(conversation.id);
    this.conversations = this.conversations.filter((c) => c.id !== conversation.id);
    this.render();
  }
};

// src/ui/FolderSuggest.ts
var import_obsidian5 = require("obsidian");
var FolderSuggest = class extends import_obsidian5.AbstractInputSuggest {
  constructor(app, inputEl) {
    super(app, inputEl);
    this.inputEl = inputEl;
  }
  getSuggestions(query) {
    const lowerQuery = query.toLowerCase();
    const matches = [];
    const visit = (folder) => {
      if (folder.path !== "/" && folder.path.toLowerCase().includes(lowerQuery))
        matches.push(folder);
      for (const child of folder.children) {
        if (child instanceof import_obsidian5.TFolder)
          visit(child);
      }
    };
    visit(this.app.vault.getRoot());
    return matches.slice(0, 20);
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
  }
  selectSuggestion(folder) {
    this.setValue(folder.path);
    this.inputEl.trigger("input");
    this.close();
  }
};

// src/views/ChatView.ts
var CHAT_VIEW_TYPE = "cited-chat";
var ChatView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.inputEl = null;
    // Preserved across re-renders (full rebuild on every store "change", same
    // as PendingChangesView) so an external event -- e.g. markFileStale
    // firing because the user edited an unrelated note in another pane --
    // doesn't wipe out a question they're mid-typing here.
    this.draftText = "";
    // Per-question, not per-conversation: the user can narrow or widen scope
    // freely between questions in the same conversation. Empty string means
    // the whole vault. Preserved across re-renders for the same reason as
    // draftText above.
    this.draftScopePath = "";
    this.render = () => {
      const container = this.contentEl;
      container.empty();
      container.addClass("cited-chat-view");
      const header = container.createDiv({ cls: "cited-chat-header" });
      header.createEl("span", { text: "Cited", cls: "cited-chat-title" });
      const headerActions = header.createDiv({ cls: "cited-chat-header-actions" });
      headerActions.createEl("button", { text: "History", cls: "cited-btn-outline" }).addEventListener("click", () => this.openHistory());
      headerActions.createEl("button", { text: "New conversation", cls: "cited-btn-solid" }).addEventListener("click", () => void this.plugin.conversationStore.startNewConversation());
      const history = container.createDiv({ cls: "cited-chat-history" });
      const conversation = this.plugin.conversationStore.getConversation();
      const loading = this.plugin.conversationStore.isLoading();
      if (conversation.turns.length === 0 && !loading) {
        history.createDiv({ cls: "cited-status", text: "Ask a question about your vault to get started." });
      }
      for (const turn of conversation.turns) {
        this.renderTurn(history, turn);
      }
      const error = this.plugin.conversationStore.getError();
      if (error)
        history.createDiv({ cls: "cited-status cited-status-error", text: `Error: ${error}` });
      if (loading)
        this.renderProgress(history);
      history.scrollTop = history.scrollHeight;
      this.renderInputRow(container, loading);
    };
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Cited";
  }
  getIcon() {
    return "quote-glyph";
  }
  async onOpen() {
    this.plugin.conversationStore.on("change", this.render);
    this.render();
  }
  async onClose() {
    this.plugin.conversationStore.off("change", this.render);
  }
  /** Live "how far along is it" status while a query is running, built from
   *  ConversationStore's progress state (populated turn-by-turn as the
   *  stream-json log arrives -- see queryVault.ts's runVaultQuery). Falls
   *  back to a generic message before the first assistant turn has streamed
   *  in yet (there's always a brief gap while claude starts up). */
  renderProgress(container) {
    const progress = this.plugin.conversationStore.getProgress();
    const wrapper = container.createDiv({ cls: "cited-status cited-progress" });
    if (!progress) {
      wrapper.createDiv({ cls: "cited-progress-label", text: "Starting search\u2026" });
      return;
    }
    const percent = Math.min(100, Math.round(progress.turn / progress.maxTurns * 100));
    const bar = wrapper.createDiv({ cls: "cited-progress-bar" });
    bar.createDiv({ cls: "cited-progress-bar-fill" }).style.width = `${percent}%`;
    wrapper.createDiv({
      cls: "cited-progress-label",
      text: `${percent}% \u2014 ${progress.label}`
    });
  }
  renderTurn(container, turn) {
    const turnEl = container.createDiv({ cls: "cited-turn" });
    if (turn.scopePath) {
      turnEl.createDiv({ cls: "cited-badge cited-badge-scope", text: `in ${turn.scopePath}` });
    }
    turnEl.createDiv({ cls: "cited-turn-question", text: turn.question });
    const answerEl = turnEl.createDiv({ cls: "cited-turn-answer" });
    void import_obsidian6.MarkdownRenderer.render(this.app, turn.answer, answerEl, "", this).then(() => {
      insertDomMarkers(answerEl, turn.claims, (claimId) => this.plugin.conversationStore.focusClaim(claimId));
    });
    if (turn.claims.length > 0) {
      const actions = turnEl.createDiv({ cls: "cited-turn-actions" });
      actions.createEl("button", { text: "Export to note", cls: "cited-btn-accent" }).addEventListener("click", () => {
        void exportAnswerToNote(this.app, turn, this.plugin.settings.citationsFolder).catch((err) => {
          new import_obsidian6.Notice(`Cited: export failed: ${errorMessage(err)}`);
        });
      });
    }
  }
  renderInputRow(container, loading) {
    const scopeRow = container.createDiv({ cls: "cited-chat-scope-row" });
    scopeRow.createSpan({ cls: "cited-chat-scope-label", text: "Search in" });
    const scopeInput = scopeRow.createEl("input", {
      cls: "cited-chat-scope-input",
      attr: { type: "text", placeholder: "Entire vault" }
    });
    scopeInput.value = this.draftScopePath;
    scopeInput.disabled = loading;
    scopeInput.addEventListener("input", () => {
      this.draftScopePath = scopeInput.value;
    });
    new FolderSuggest(this.app, scopeInput);
    const row = container.createDiv({ cls: "cited-chat-input-row" });
    const input = row.createEl("textarea", {
      cls: "cited-chat-input",
      attr: { rows: "2", placeholder: "Ask a question about your vault\u2026" }
    });
    input.value = this.draftText;
    input.disabled = loading;
    input.addEventListener("input", () => {
      this.draftText = input.value;
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit();
      }
    });
    this.inputEl = input;
    const askBtn = row.createEl("button", { text: "Ask", cls: "cited-btn-solid" });
    askBtn.disabled = loading;
    askBtn.addEventListener("click", () => this.submit());
  }
  submit() {
    var _a, _b;
    if (this.plugin.conversationStore.isLoading())
      return;
    const question = ((_b = (_a = this.inputEl) == null ? void 0 : _a.value) != null ? _b : "").trim();
    if (!question)
      return;
    const scopePath = this.draftScopePath.trim().replace(/^\/+|\/+$/g, "");
    this.draftText = "";
    void this.plugin.conversationStore.askQuestion(question, scopePath || null);
  }
  openHistory() {
    const archived = this.plugin.conversationStore.listArchived();
    new ConversationHistoryModal(
      this.app,
      archived,
      (id) => this.plugin.conversationStore.openConversation(id),
      (id) => this.plugin.conversationStore.deleteConversation(id)
    ).open();
  }
};

// src/settings.ts
var import_obsidian7 = require("obsidian");
var DEFAULT_SETTINGS = {
  maxTurns: 8,
  citationsFolder: "Citations",
  openChatOnLaunch: true,
  openSourcesOnLaunch: true
};
var MIN_MAX_TURNS = 1;
var MAX_MAX_TURNS = 30;
var CitedSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian7.Setting(containerEl).setName("Max search turns per question").setDesc(
      `How many agentic search/read round trips (claude's own --max-turns) a single question is allowed before it has to answer with whatever it's found so far (${MIN_MAX_TURNS}-${MAX_MAX_TURNS}). Higher allows more thorough searches of a large vault at the cost of slower, more expensive queries.`
    ).addSlider(
      (slider) => slider.setLimits(MIN_MAX_TURNS, MAX_MAX_TURNS, 1).setValue(this.plugin.settings.maxTurns).onChange(async (value) => {
        this.plugin.settings.maxTurns = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("Citations export folder").setDesc(`Vault folder "Export to note" saves into (created automatically if it doesn't exist yet). Leave blank for the vault root.`).addText(
      (text) => text.setPlaceholder("e.g. Citations").setValue(this.plugin.settings.citationsFolder).onChange(async (value) => {
        this.plugin.settings.citationsFolder = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("Open on launch").setHeading();
    new import_obsidian7.Setting(containerEl).setName("Open chat panel on launch").setDesc("Automatically open the Cited chat panel when Obsidian starts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openChatOnLaunch).onChange(async (value) => {
        this.plugin.settings.openChatOnLaunch = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("Open sources panel on launch").setDesc("Automatically open the Cited sources (citations) panel when Obsidian starts.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.openSourcesOnLaunch).onChange(async (value) => {
        this.plugin.settings.openSourcesOnLaunch = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("History").setHeading();
    new import_obsidian7.Setting(containerEl).setName("Clear conversation history").setDesc(
      "Permanently deletes every archived conversation (up to 50 are kept). Your current, active conversation is not affected. This can't be undone -- individual conversations can also be deleted one at a time from the History picker in the chat panel."
    ).addButton(
      (button) => button.setButtonText("Clear history").setWarning().onClick(async () => {
        const confirmed = await ConfirmModal.confirm(
          this.app,
          "Clear conversation history?",
          "This permanently deletes every archived conversation. This can't be undone.",
          "Clear history"
        );
        if (!confirmed)
          return;
        await this.plugin.conversationStore.clearHistory();
        new import_obsidian7.Notice("Cited: conversation history cleared.");
      })
    );
  }
};

// src/main.ts
var CitedPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.claudeBin = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new CitedSettingTab(this.app, this));
    this.conversationStore = new ConversationStore(
      path4.join(this.getPluginDir(), "conversations.json"),
      (question, resumeSessionId, scopePath, onProgress) => this.runQuery(question, resumeSessionId, scopePath, onProgress),
      (vaultRelativePath) => this.statMtime(vaultRelativePath)
    );
    await this.conversationStore.load();
    this.registerView(CHAT_VIEW_TYPE, (leaf) => new ChatView(leaf, this));
    this.registerView(CITED_VIEW_TYPE, (leaf) => new CitedView(leaf, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (file instanceof import_obsidian8.TFile)
          this.conversationStore.markFileStale(file.path);
      })
    );
    this.addRibbonIcon("quote-glyph", "Open Cited", () => void this.revealViews());
    this.addCommand({
      id: "ask",
      name: "Ask about your vault",
      callback: () => void this.revealViews()
    });
    this.app.workspace.onLayoutReady(() => void this.revealViews({ onlyIfEnabled: true }));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getVaultBasePath() {
    const adapter = this.app.vault.adapter;
    if (!(adapter instanceof import_obsidian8.FileSystemAdapter)) {
      throw new Error("Cited requires a desktop vault (FileSystemAdapter)");
    }
    return adapter.getBasePath();
  }
  getPluginDir() {
    return path4.join(this.getVaultBasePath(), this.app.vault.configDir, "plugins", this.manifest.id);
  }
  async getClaudeBin() {
    if (!this.claudeBin)
      this.claudeBin = await resolveClaudeBin();
    return this.claudeBin;
  }
  async runQuery(question, resumeSessionId, scopePath, onProgress) {
    const claudeBin = await this.getClaudeBin();
    const prompt = buildVaultQuestionPrompt(question, scopePath);
    return runVaultQuery(claudeBin, this.getVaultBasePath(), prompt, this.settings.maxTurns, scopePath, resumeSessionId, onProgress);
  }
  statMtime(vaultRelativePath) {
    const file = this.app.vault.getAbstractFileByPath(vaultRelativePath);
    return file instanceof import_obsidian8.TFile ? file.stat.mtime : null;
  }
  /** Both panels live stacked in the right sidebar, as two sibling panes
   *  sharing one split rather than as tabs: CitedView ("Cited sources") on
   *  top, ChatView stacked directly below it via createLeafBySplit(...,
   *  "horizontal", false) off the sources leaf. Order matters -- the
   *  sources leaf has to exist first so the chat leaf has something to
   *  split off of. If sources is skipped (settings-disabled or already
   *  closed with no leaf to split from), chat falls back to its own fresh
   *  right-sidebar tab so it's never lost.
   *
   *  `onlyIfEnabled` gates each panel on its own "open on launch" setting
   *  -- used for the automatic onLayoutReady call so a user who only wants
   *  one panel auto-opened doesn't get both. The ribbon icon and command
   *  call this with no options, so manually asking Cited a question always
   *  reveals both regardless of the launch settings. */
  async revealViews(options) {
    var _a, _b, _c, _d, _e;
    const { workspace } = this.app;
    const onlyIfEnabled = (_a = options == null ? void 0 : options.onlyIfEnabled) != null ? _a : false;
    let citedLeaf = (_b = workspace.getLeavesOfType(CITED_VIEW_TYPE)[0]) != null ? _b : null;
    if (!citedLeaf && (!onlyIfEnabled || this.settings.openSourcesOnLaunch)) {
      citedLeaf = (_c = workspace.getRightLeaf(false)) != null ? _c : workspace.getLeaf("tab");
      await citedLeaf.setViewState({ type: CITED_VIEW_TYPE, active: false });
    }
    let chatLeaf = (_d = workspace.getLeavesOfType(CHAT_VIEW_TYPE)[0]) != null ? _d : null;
    if (!chatLeaf && (!onlyIfEnabled || this.settings.openChatOnLaunch)) {
      chatLeaf = citedLeaf ? workspace.createLeafBySplit(citedLeaf, "horizontal", false) : (_e = workspace.getRightLeaf(false)) != null ? _e : workspace.getLeaf("tab");
      await chatLeaf.setViewState({ type: CHAT_VIEW_TYPE, active: true });
    }
    if (citedLeaf)
      workspace.revealLeaf(citedLeaf);
    if (chatLeaf)
      workspace.revealLeaf(chatLeaf);
  }
};
